# Generated by Django 4.1.7 on 2023-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_categories',
        ),
    ]
